# Generated by Django 4.2.7 on 2024-05-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("certificate_id", models.AutoField(primary_key=True, serialize=False)),
                ("certificate_name", models.CharField(max_length=255)),
                ("issued_by", models.CharField(max_length=255)),
                ("valid_until", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Suplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SupplyChain",
            fields=[
                (
                    "supply_chain_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("from_location", models.CharField(max_length=255)),
                ("to_location", models.CharField(max_length=255)),
                ("transport_mode", models.CharField(max_length=255)),
                ("carbon_emissions", models.IntegerField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.suplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "risk_assessment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("risk_level", models.CharField(max_length=255)),
                ("assessment_date", models.CharField(max_length=255)),
                ("assessor", models.CharField(max_length=255)),
                ("comments", models.TextField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.suplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("units_in_stock", models.IntegerField()),
                (
                    "supplier_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.suplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compliance",
            fields=[
                ("compliance_id", models.AutoField(primary_key=True, serialize=False)),
                ("compliance_date", models.DateTimeField()),
                (
                    "certificate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.certificate",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.product",
                    ),
                ),
                (
                    "supplier_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.suplier",
                    ),
                ),
            ],
        ),
    ]
