# Generated by Django 4.2.7 on 2024-05-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("shipment_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_category", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("units_in_stock", models.IntegerField()),
                ("country_of_production", models.CharField(max_length=255)),
                ("DOP_manufacture", models.DateTimeField()),
                ("geolocation", models.CharField(max_length=255)),
                ("transport_mode", models.CharField(max_length=255)),
                ("carbon_emissions", models.IntegerField()),
                ("start_location", models.CharField(max_length=255)),
                ("destination_location", models.CharField(max_length=255)),
                ("proof_certificate_1", models.IntegerField()),
                ("proof_certificate_2", models.IntegerField()),
                ("self_confirmation", models.CharField(max_length=255)),
                ("signature", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("form_submited_date", models.DateTimeField()),
                (
                    "certificate_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.certificate",
                    ),
                ),
                (
                    "supplier_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.suplier",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="compliance",
            name="product_id",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="compliance",
            name="shipment_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.shipment",
            ),
        ),
    ]
