# Generated by Django 4.2.7 on 2024-05-24 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_suplier_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suplier",
            old_name="user",
            new_name="user_id",
        ),
    ]
