# Generated by Django 4.2.7 on 2024-05-24 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_rename_user_suplier_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suplier",
            old_name="user_id",
            new_name="user",
        ),
    ]
