# Generated by Django 4.2.7 on 2024-05-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_rename_user_id_suplier_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliance",
            name="compliant",
            field=models.CharField(default="no", max_length=255),
        ),
    ]
