# Generated by Django 4.2.7 on 2024-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_compliance_compliant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="certificate_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="product_category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="proof_certificate_1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="proof_certificate_2",
            field=models.CharField(max_length=255),
        ),
    ]
